### ISSUE TITLE
Fork to a differend PoW to prevent double spend attacks

### ISSUE THREAD

**Issue by sebseb7** [LetheanMovement/lethean#143]
Lethean is very vulnerable to double spend attacks because of Pow and Daa choices. 

there is a 4 btc orderbook, and in case something happens to it, it will be blamed on me.

**Comment by ronnylov** [comment]
I suggest you create your own coin and show the world the perfect coin. You seem to know how it should be done. Then we can all fork your wonderful creation.

**Comment by sebseb7** [comment]
So you want me to write the code for this fix?

**Comment by Venthos** [comment]
Forking to a different/unique POW with the entirety of the argument being that NiceHash/MRR will not have a large rig rental pool for it ([Source](https://github.com/graft-project/GraftNetwork/issues/191)) is extremely short sighted and attempts to solve an issue entirely by "security through obscurity".  This would be incredibly reckless.

To your point, the issue at hand absolutely does exist; which is the existence of a large rentable hashrate many factors larger than the network.  This hashrate could then be leveraged for malicious purposes.  What you have proposed is not a fix in even the most generous of terms, however.  The best case scenario is that you end up actually lowering the network hashrate even further by increasing the barrier of entry to mining for legitimate users.  No mining programs would support it initially, and we would have to hope that the popular mining programs would even care to accept pull requests for such a niche algorithm.  Let alone hope that it would be done in a timely manner.  If wide-spread acceptance became reality, then we're right back to square one since it would be trivial for NiceHash/MRR to support the algorithm.  The only benefit you're arguing from at that point is an uncontrolled artificial delay in public rental availability until NiceHash/MRR deem it profitable to add as a drop-down selection.  That does not seem like a good technical investment to me.

Reviewing potential solutions to secure the network from 51% attacks and other malicious actions is absolutely worthy and necessary.  To be clear, I am not arguing against the existence of this problem or suggesting that a solution shouldn't be looked into.  Simply put, the solution proposed here provides virtually no tangible benefit outside of an unknown period of security through obscurity.  The network would be just as susceptible to anyone specifically targeting the project. Changing PoW, for the moment, serves primarily as a means to be "resistant" to ASICs on the network.

**Comment by ronnylov** [comment]
When millions of people need LTHN coins to use VPN we will get plenty of hashrate to outperform Monero. Minor malicious mining pools trying to do 51% attacks will be a problem of the past.

**Comment by Venthos** [comment]
I don't have one.  An absence of a good solution does not mean that a project should enact a bad decision out of default.  Most cryptocurrency were initially susceptible to a 51% attack until their network grew.  While the long term solution is to grow the network, until/unless a good solution comes along the only option seems to be to continue to monitor for attacks on the blockchain and work closely with exchanges to mitigate any attacks as expediently as possible.  Does this mean it is a risk to participate in a project that does not have massive network hashrates (Lethean or otherwise)? Sure.  It absolutely does.  It is a risk that should not be taken lightly, and as far as I can see is not something taken lightly by the Lethean Team either.

**Comment by sebseb7** [comment]
" and work closely with exchanges to mitigate any attacks as expediently as possible"

the only option for the exchange is a delist.

**Comment by ronnylov** [comment]
We use the same PoW as Monero. Do they delist Monero? Better use the same than inttroduce bugs creating something new. In time we get big enough that no scammy miners can afford any more 51% attacks. Exchanges prefer serious coins like Lethean that handle these things professionally. Shitty scammers will always bite the dust in the end.

**Comment by Netucet** [comment]
@sebseb7 Maybe if you stop using your mining pool to scam and hack projects (turtle, ultranote, stellite etc.) - maybe then people would listen to you and begin to consider you being usefull?

**Comment by sebseb7** [comment]
If I can break it by running a pool, they shoud stop their coins instead and begin from scratch. Also never ever hacked Turlte or Stellite. 

"maybe then people would listen to you and begin to consider you being usefull"

that's up to them. I don't care whether these coins die.

**Comment by RocksteadyTC** [comment]
![image](https://user-images.githubusercontent.com/34389545/47882701-615e5480-ddf8-11e8-971f-9b299353fbba.png)

**Comment by valiant1x** [comment]
Solving the problem of 51% attacks relies upon either:
* Centralizing the blockchain to store/retrieve checkpoints regularly from a 'trusted' source
* Keeping a decentralized infrastructure but having enough network hash power that the cost of a 51% attack is inaccessible or impractical
* Removing the self-healing nature of the blockchain and preventing re-organizations over a certain threshold

These same problems and solutions exist even when adopting a custom POW as @Venthos described above.

At the present time our team is comfortable with the solution of requiring high confirmations at exchanges. As the number of confirmations for a deposit increase, the resources to execute a successful 51% attack increase in parallel. At the same time, we are doing everything in our power to promote LTHN and thus bolster hash rate. We are also actively working to make mining more accessible (look for the return of in-wallet pooled mining soon).

For now, I do not believe this discussion is constructive or generating pragmatic solutions, so I am closing it. Please tag me @valiant1x to reopen.
